name: Build iOS Tweak (Theos)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Theos Dependencies
        run: brew install ldid

      - name: Setup Theos
        run: |
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          # By NOT downloading theos/sdks here, we force Theos to use the 
          # system Xcode SDK which contains the missing files Swift needs.

      - name: Compile Tweak
        run: |
          make FINALPACKAGE=1 TARGET="iphone:clang:latest:14.0"

      - name: Extract and Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Dylib
          path: .theos/obj/**/*.dylib
          include-hidden-files: true
